### ISSUE TITLE
rpc.statd and rpc.mountd listening to ALL address 

### ISSUE THREAD

**Issue by rajubi1981** [andreas-gruenbacher/nfs-utils#1]
The rpc.statd and rpc.mountd utilities required for NFS mount are listening to 0.0.0.0 address.

tcp 0 0 0.0.0.0:32765 0.0.0.0:* LISTEN 25835/rpc.statd
tcp 0 0 0.0.0.0:32767 0.0.0.0:* LISTEN 2946/rpc.mountd
udp 0 0 0.0.0.0:32765 0.0.0.0:* 25835/rpc.statd
udp 0 0 0.0.0.0:32766 0.0.0.0:* 25835/rpc.statd
udp 0 0 0.0.0.0:32767 0.0.0.0:* 2946/rpc.mountd

While starting the rpc.statd there is one option as ( -n / --name ) to pass the hostname / IP address. But if we pass with the option and try to start the rpc.statd , still it listens to all ports instead of the hostname / Ip address specified in the option.

I would like to know what is ( -n ) option used for ? How do I make the rpc.statd and rpc.mountd listen to specific address instead of 0.0.0.0 which means allow all address.

Platform tested on : RHEL5.x

**Comment by andreas-gruenbacher** [comment]
I'm the wrong person to ask, sorry. Try here: http://linux-nfs.org/

**Comment by nh2** [comment]
> rpc.mountd listen to specific address instead of 0.0.0.0

Since this is an early result in Google, posting here as well even though it's not the upstream project:

**It's impossible**, the `0.0.0.0` [is hardcoded](https://serverfault.com/questions/1110431/how-to-specify-a-specific-bind-address-for-nfs-kernel-server-on-debian-11-4/1163083#1163083).
