### ISSUE TITLE
there is a issue in auth_reload.

### ISSUE THREAD

**Issue by pengdonglin137** [andreas-gruenbacher/nfs-utils#2]
https://github.com/andreas-gruenbacher/nfs-utils/blob/2fba244ccc918448f2a8c838dcda6ac1ad5d45cb/utils/mountd/auth.c#L100

when the function `auth_reload` is invoked for the first time, file descriptor 0 will be closed unconditionly.

**Comment by andreas-gruenbacher** [comment]
Hello, this is a fork of the original nfs-utils repository at http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=summary. Please report any issues against that. (Chances are that the bug has already been fixed in the years since this fork has last been touched.) Thank you!
